# Environment file for ADC Summary tools.
name: afc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - act-atmos
  - matplotlib
  - xarray
  - pandas
  - dask
  - numpy
  - scipy
