# dsname: Datastream name to pull data from
# dsname2: Secondary datastream(s) to include and merge
# t_delta: Script will resample data to 1 min.  If gaps are longer set this appropriately
# workers: Set to 1 in the case of radar data so it doesn't crash the system
conf = {
    'site': 'bnf',
    'facility': 'M1',
    'start_date': '2024-9-01',
    'end_date': '2025-10-01',
    'outname': '/home/theisen/Code/AFC_Summary/images/bnf/bnf_data_avail.pdf', #options are png, pdf, etc
    'chart_style': 'linear',
    'info_style': 'simple',
    'data_path': '/data/archive',
    'dqr_table': True,
    'doi_table': True, #this will remove the DOI from besides the plots
    'instruments':{
        'aeri': {'dsname': 'aerisummaryM1.b1'},
        'asi': {'dsname': 'asiskycoverM1.b1'},
        'ceil': {'dsname': 'ceilM1.b1'},
        'dl': {'dsname': 'dlfptM1.b1', 't_delta': 60},
        'ecor': {'dsname': '30ecorM1.b1', 't_delta': 30},
        'gndrad': {'dsname': 'gndrad60sM1.b1'},
        'hsrl': {'dsname': 'hsrlM1.a1'},
        'irt': {'dsname': 'irtM1.b1'},
        'ldis': {'dsname': 'ldM1.b1'},
        'maws': {'dsname': 'mawsM1.b1'},
        'met': {'dsname': 'metM1.b1'},
        'mfrsr': {'dsname': 'mfrsr7nchM1.b1'},
        'mpl': {'dsname': 'mplpolfsM1.b1'},
        'mwr3c': {'dsname': 'mwr3cM1.b1'},
        'rl': {'dsname': 'rlM1.a0'},
        'skyrad': {'dsname': 'skyrad60sM1.b1'},
        'sonde': {'dsname': 'sondewnpnM1.b1', 't_delta': 1440./3},
        'vdis': {'dsname': 'vdisM1.b1'},
        'wb': {'dsname': 'wbpluvio2M1.a1'},
        'aeriS20': {'dsname': 'aerisummaryS20.b1'},
        'dlS20': {'dsname': 'dlfptS20.b1', 't_delta': 60},
        'mwr3cS20': {'dsname': 'mwr3cS20.b1'},
        'ecorS20': {'dsname': '30ecorS20.b1', 't_delta': 30},
        'gndradS20': {'dsname': 'gndrad60sS20.b1'},
        'irtS20': {'dsname': 'irtS20.b1'},
        'metS20': {'dsname': 'metS20.b1'},
        'mfrsrS20': {'dsname': 'mfrsr7nchS20.b1'},
        'sebsS20': {'dsname': 'sebsS20.b1'},
        'skyradS20': {'dsname': 'skyrad60sS20.b1'},
        'stampS20': {'dsname': 'stampS20.b1'},
        'aeriSi30': {'dsname': 'aerisummaryS30.b1'},
        'dlS30': {'dsname': 'dlfptS30.b1', 't_delta': 60},
        'mwr3cS30': {'dsname': 'mwr3cS30.b1'},
        'ecorS30': {'dsname': '30ecorS30.b1', 't_delta': 30},
        'gndradS30': {'dsname': 'gndrad60sS30.b1'},
        'irtS30': {'dsname': 'irtS30.b1'},
        'metS30': {'dsname': 'metS30.b1'},
        'mfrsrS30': {'dsname': 'mfrsr7nchS30.b1'},
        'sebsS30': {'dsname': 'sebsS30.b1'},
        'skyradS30': {'dsname': 'skyrad60sS30.b1'},
        'stampS30': {'dsname': 'stampS30.b1'},
        'aeriS40': {'dsname': 'aerisummaryS40.b1'},
        'dlS40': {'dsname': 'dlfptS40.b1', 't_delta': 60},
        'mwr3cS40': {'dsname': 'mwr3cS40.b1'},
        'ecorS40': {'dsname': '30ecorS40.b1', 't_delta': 30},
        'gndradS40': {'dsname': 'gndrad60sS40.b1'},
        'irtS40': {'dsname': 'irtS40.b1'},
        'metS40': {'dsname': 'metS40.b1'},
        'mfrsrS40': {'dsname': 'mfrsr7nchS40.b1'},
        'sebsS40': {'dsname': 'sebsS40.b1'},
        'skyradS40': {'dsname': 'skyrad60sS40.b1'},
        'stampS40': {'dsname': 'stampS40.b1'},
    }
}
