# dsname: Datastream name to pull data from
# dsname2: Secondary datastream(s) to include and merge
# t_delta: Script will resample data to 1 min.  If gaps are longer set this appropriately
# workers: Set to 1 in the case of radar data so it doesn't crash the system
conf = {
    'site': 'hou',
    'facility': 'M1',
    'start_date': '2021-10-01',
    'end_date': '2022-10-01',
    'outname': '/home/theisen/Code/AFC_Summary/images/hou/hou_M1_data_availability.pdf', #options are png, pdf, etc
    'chart_style': 'linear',
    'info_style': 'simple',
    'data_path': '/data/archive',
    'dqr_table': True,
    'doi_table': True, #this will remove the DOI from besides the plots
    'instruments':{
        'acsm': {'dsname': 'aosacsmM1.b1', 't_delta': 30},
        'aeth': {'dsname': 'aosaeth2spotM1.a1'},
        'aosmet': {'dsname': 'aosmetM1.a1'},
        'ccn': {'dsname': 'aosccn2colaM1.b1'},
        'co-analyzer': {'dsname': 'aoscoM1.b1'},
        'cpc': {'dsname': 'aoscpcf1mM1.b1'},
        'cpc': {'dsname': 'aoscpcu1mM1.b1'},
        'htdma': {'dsname': 'aoshtdmaM1.a1', 't_delta': 60},
        'nephelometer': {'dsname': 'aosnephdry1mM1.b1'},
        'nephelometer': {'dsname': 'aosnephwet1mM1.b1'},
        'ozone': {'dsname': 'aoso3M1.b1'},
        'psap': {'dsname': 'aospsap3w1mM1.b1'},
        'smps': {'dsname': 'aossmpsM1.b1', 't_delta': 30},
        'so2': {'dsname': 'aosso2M1.b1'},
        'uhsas': {'dsname': 'aosuhsasM1.b1'},
        'aeri': {'dsname': 'aerisummaryM1.b1'},
        'ceil': {'dsname': 'ceilM1.b1'},
        'dl': {'dsname': 'dlfptM1.b1', 't_delta': 60},
        'ecor': {'dsname': '30ecorM1.b1', 't_delta': 30},
        'gndrad': {'dsname': 'gndrad60sM1.b1'},
        'gndirt': {'dsname': 'gndirtM1.b1'},
        'irt': {'dsname': 'irtM1.b1'},
        #'kazr': {'dsname': 'kazrcfrgeM1.a1', 'workers': 1, 'data_path': '/data/datastream'},
        #'kasacr': {'dsname': 'kasacrcfrM1.a1', 'workers': 1, 'data_path': '/data/datastream'},
        'ldis': {'dsname': 'ldM1.b1'},
        'maws': {'dsname': 'mawsM1.b1'},
        'met': {'dsname': 'metM1.b1'},
        'mfr': {'dsname': 'mfr7nch10mM1.b1'},
        'mfrsr': {'dsname': 'mfrsr7nchM1.b1'},
        'mpl': {'dsname': 'mplpolfsM1.b1'},
        'mwr': {'dsname': 'mwrlosM1.b1'},
        'mwr3c': {'dsname': 'mwr3cM1.b1'},
        'mwrhf': {'dsname': 'mwrhfM1.b1'},
        'nfov': {'dsname': 'nfov2chM1.b1'},
        'rwp': {'dsname': '915rwpwindconX10.a1', 'dsname2': '915rwpprecipconX10.a1', 't_delta': 60},
        '1290rwp': {'dsname': '1290rwpwindconM1.a1', 'dsname2': '1290rwpprecipconM1.a1', 't_delta': 60},
        'sebs': {'dsname': 'sebsM1.b1', 't_delta': 30},
        'skyrad': {'dsname': 'skyrad60sM1.b1'},
        'tsi': {'dsname': 'tsiskycoverM1.b1'},
        'vdis': {'dsname': 'vdisM1.b1'},
        'wb': {'dsname': 'wbpluvio2M1.a1'},
        #'xsacr': {'dsname': 'xsacrcfrM1.a1', 'workers': 1, 'data_path': '/data/datastream'},
    }
}
